import { defineCollection, z } from 'astro:content';

const home = defineCollection({
  type: 'data',
  schema: z.object({
    metaTitle: z.string(),
    metaDescription: z.string().optional(),
    navLanguageToggleLabel: z.string(),
    navLanguageToggleAria: z.string(),
    sectionGalleryLabel: z.string(),
    sectionGalleryHeading: z.string(),
    sectionGalleryBody: z.string(),
    sectionGalleryCaptionOne: z.string(),
    sectionGalleryCaptionTwo: z.string(),
    sectionGalleryCaptionThree: z.string(),
    galleryImageAltPrefix: z.string(),
    sliderGalleryAriaLabel: z.string(),
    sliderGalleryLabel: z.string(),
    sectionAmenitiesLabel: z.string(),
    sectionAmenitiesHeading: z.string(),
    sectionAmenitiesBody: z.string(),
    sectionAmenitiesList: z.array(z.string()),
    sectionAmenitiesHighlight: z.string(),
    sectionAmenitiesPianoAlt: z.string(),
    sectionOutdoorLabel: z.string(),
    sectionOutdoorHeading: z.string(),
    sectionOutdoorBody: z.string(),
    sectionOutdoorHighlights: z.array(z.string()),
    sectionEnvironmentLabel: z.string(),
    sectionEnvironmentHeading: z.string(),
    sectionEnvironmentBody: z.string(),
    sectionEnvironmentHighlights: z.array(z.string()),
    sectionOptionalLabel: z.string(),
    sectionOptionalHeading: z.string(),
    sectionOptionalBody: z.string(),
    sectionOptionalHighlights: z.array(z.string()),
    sectionPhilosophyLabel: z.string(),
    sectionPhilosophyHeading: z.string(),
    sectionPhilosophyBody: z.string(),
    sectionPhilosophyHighlights: z.array(z.string()),
    sectionRetreatHeading: z.string(),
    sectionRetreatBody: z.string(),
    sectionRetreatHighlights: z.array(z.string()),
    heroEyebrow: z.string().optional(),
    heroHeadline: z.string(),
    heroBody: z.array(z.string()),
    heroFeatures: z.array(z.string()),
    heroPrimaryCtaLabel: z.string(),
    heroPrimaryCtaHref: z.string(),
    heroSecondaryCtaLabel: z.string(),
    heroSecondaryCtaHref: z.string(),
    heroAlt: z.string(),
    heroSubheadline: z.string().optional(),
    heroCta: z.string().optional(),
    footerTagline: z.string(),
    footerContactLabel: z.string(),
    footerAirbnbRatingLabel: z.string(),
    footerImprintLabel: z.string(),
    footerPrivacyLabel: z.string(),
    footerRightsLabel: z.string(),
  }),
});

export const collections = { home };
